version: "3.7"
services:
  api:
    build:
      context: ./src
      target: api
      dockerfile: ./config/Dockerfile
    ports:
      - "9000:9000"
    # volumes:
    #   - ./src/:/app/
    env_file:
      - src/.env
    depends_on:
      redis:
        condition: service_started

  worker:
    build:
      context: ./src
      target: worker
      dockerfile: ./config/Dockerfile
    volumes:
      - ./src:/app/
    env_file:
      - src/.env
    depends_on:
      redis:
        condition: service_started

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
