version: "3.7"
services:
  api:
    build:
      context: ./src
      dockerfile: ./Dockerfile.api
    ports:
      - "9000:9000"
    # volumes:
    #   - .:/app/
    env_file:
      - src/.env
    depends_on:
      redis:
        condition: service_started

  worker:
    build:
      context: ./src
      dockerfile: ./Dockerfile.worker
    # volumes:
    #   - .:/app/
    env_file:
      - src/.env
    depends_on:
      redis:
        condition: service_started

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
