FROM python:3.11-slim

WORKDIR /app/

COPY requirements-dev.txt requirements-dev.txt
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY manage.py /app/
COPY entrypoint_worker.sh /app/entrypoint.sh

COPY image_describer /app/image_describer

CMD ["bash", "entrypoint.sh"]
